id: P000586
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:48:34.156714
source_metadata:
  id: bdr:W16515
  title: གསུང་འབུམ། བློ་བཟང་འཇམ་དབྱངས་སྨོན་ལམ
  author: ''
  volumes:
    b6482bae5c00437d99a7411e3114930c:
      image_group_id: I3891
      title: ''
      volume_number: 1
      total_pages: 812
      base_file: v001.txt
    679fcc4e860c43c389e25f66010c7cd5:
      image_group_id: I3892
      title: ''
      volume_number: 2
      total_pages: 816
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
