id: I7BBB8C28
legacy_id: P000586
ocr_import_info:
  bdrc_scan_id: W16515
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T17:33:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:55:12.657840+00:00'
last_modified: 2022-08-30 22:57:08.636879
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W16515
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW16515
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་འཇམ་དབྱངས་སྨོན་ལམ།
  author: ཀེའུ་ཚང་འཇམ་དབྱངས་སྨོན་ལམ།
statistics:
  ocr_word_mean_confidence_index: 0.6542339608871057
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I3892:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3892
      total_pages: 816
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3892.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6467676138388386
    legacy_id: v002
  I3891:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3891
      total_pages: 812
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3891.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6626118094835803
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
